### ISSUE TITLE
Remove the `print_assembly` option from Smart in its entirety.

### ISSUE THREAD

**Issue by finsberg** [justinlaughlin/stubs#128]
I think we should remove the `print_assembly` option from Smart in its entirety.

As we are now using the logger for printing, I think it should only be the log-level that determines if we want to print or not, not a secondary parameter ("print_assembly"), that is passed to the `SmartSNESProblem` as the variable `verbose`. @finsberg  any thoughts on this?

_Originally posted by @jorgensd in https://github.com/RangamaniLabUCSD/smart/pull/124#discussion_r1252628314_

**Comment by emmetfrancis** [comment]
This sounds reasonable to me, I can make this change fairly easily. I think the logic behind having the extra flag was that the assembly process can be quite verbose, so a user might want to suppress that output separately. But most of the output controlled by this is set to DEBUG, so that shouldn't be much of a concern, I think.
